# Generated by Django 4.1.7 on 2023-03-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
