# Generated by Django 4.1.7 on 2023-04-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
